### ISSUE TITLE
issue with running files

### ISSUE THREAD

**Issue by Capester1** [danielweidman/pixmob-ir-reverse-engineering#36]
Hello,

I am trying to use an Intel MacBook Air to run the python scripts.

I was wondering how you are supposed to download the files and then run them to light up the pixmob bracelet. I currently tried downloading the config.py file and the demo_single_effect.py files to a folder on my desktop. Are there others that I need to download? How do you run the files? Any help is appreciated.

Thanks in advance!

**Comment by sean1983** [comment]
Hi, 

Yes there is other files You  should see them in Imports at the begining of each python script,

- pixmob_conversion_func.py
- effect_definitions.py

Also make sure that the modules are installed too, like PySerial using PIP INSTALL

Be sure your directory structure is correct matching the repo.

You would probably be best cloning or downloading all the files from the Repo.

Check your Serial Port and Baud Rate to defined correctly in config.py

Hope this helps 


Sean

**Comment by Capester1** [comment]
Thank you. It says that it has successfully sent the code to the arduino. However, I am testing with a standard visible LED, and I am not getting it to light up. however, the 'L' LED on the arduino UNO circuit board is illuminating briefly when I run the demo code. Is there something that I should change in the arduino code? I already have it assigned to what pin the LED circuit is connected to. Thanks.

**Comment by Capester1** [comment]
Hi,

It appears to be a PixMob X3, according to pictures on the website. It is from the Taylor swift 2023 concerts. 

Is there anything else other than the data pin that is being used that needs to be entered into the PixMob_Transmitter_Arduino.ino file? 

Thanks.

**Comment by sean1983** [comment]
Hi again,

I guess it's tbis model you mean that Talor Swift uses.

![20230614_173932.jpg](https://github.com/danielweidman/pixmob-ir-reverse-engineering/assets/6167947/58f2323d-426a-4bf9-81a4-b52d21954f9d)

![20230614_173629.jpg](https://github.com/danielweidman/pixmob-ir-reverse-engineering/assets/6167947/b8e3d4ac-3f47-45fa-9060-f9e357cf9fc1)

It might be worth checking the batteries,  These don't hols charge very long,

With this model they made them NON-Recyclable by heat-staking them together,  but you can snip the snip the back of the melted plastic stakes and seperate it to test or  replace the batteries.  If cut flush it clips back together again.

![20230614_175607.jpg](https://github.com/danielweidman/pixmob-ir-reverse-engineering/assets/6167947/f81e0111-ad5f-4f5f-b49d-22697ccd727f)

![20230614_180014.jpg](https://github.com/danielweidman/pixmob-ir-reverse-engineering/assets/6167947/58c6ae2c-4772-44d3-a922-39f78f9a130b)

![20230614_180158.jpg](https://github.com/danielweidman/pixmob-ir-reverse-engineering/assets/6167947/660daca7-f731-4ec2-9259-f98a352ed6e5)


With the Arduino script it is just the GPIO Pin that needs to be specified.

May I ask what type of Arduino you are using ?

**Comment by Capester1** [comment]
Hello, Thank you for all of your help. I was able to get it to light up by setting `WAIT_BEFORE_SEND = True ` in Config.py.
